[build-system]
requires = [
  "setuptools>=80",
  "cmake>=3.25",
  "typing_extensions",
]
build-backend = "setuptools.build_meta"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
# E/F = standard flake8/pyflakes, I = isort
select = ["E", "F", "I"]
