name: 'Run tests'
description: 'Run Python and C++ tests on Windows'

runs:
  using: 'composite'
  steps:
    - name: Run Python tests - CPU
      shell: bash
      env:
        DEVICE: cpu
      run: python -m unittest discover python/tests -v

    - name: Run CPP tests - CPU
      shell: bash
      env:
        DEVICE: cpu
      run: ./build/cpp/mlx/tests.exe -tce="*gguf*"
