name: 'Run tests on Windows'

runs:
  using: 'composite'
  steps:
    - name: Run CPP tests - CPU
      shell: bash
      env:
        DEVICE: cpu
      run: |
        echo "::group::CPP tests - CPU"
        ./build/tests.exe -tce="*gguf*,test random uniform"
        echo "::endgroup::"
