name: 'Build macOS'
description: 'Build C++ and Python binaries for testing on macOS'

inputs:
  cmake-args:
    description: 'The args for generating CMake project'
    required: true
  macos-target:
    description: 'The target macOS version to build for'
    required: false
    default: '26.2'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: uv pip install build setuptools

    - name: Build wheel
      shell: bash
      env:
        DEBUG: 1
        CMAKE_ARGS: ${{ inputs.cmake-args }}
        MACOSX_DEPLOYMENT_TARGET: ${{ inputs.macos-target }}
      run: python -m build -w

    - name: Build CPP only
      shell: bash
      env:
        MACOSX_DEPLOYMENT_TARGET: ${{ inputs.macos-target }}
      run: |
        if ${{ contains(inputs.cmake-args, 'CMAKE_BUILD_TYPE') }} ; then
          cmake . -B build ${{ inputs.cmake-args }}
        else
          cmake . -B build ${{ inputs.cmake-args }} \
            -DCMAKE_BUILD_TYPE=Debug
        fi
        cmake --build build -j $(sysctl -n hw.physicalcpu)
