name: 'Build and Test on macOS'
description: 'Build and test MLX on macOS'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10'
  macos-target:
    description: 'macOS target to build and test for'
    required: false
    default: '14.0'

runs:
  using: "composite"
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
          python-version: ${{ inputs.python-version }}
          activate-environment: true

    - name: Install dependencies
      shell: sh
      env:
        DEBUG: 1
        CMAKE_ARGS: "-DCMAKE_COMPILE_WARNING_AS_ERROR=ON"
        MACOSX_DEPLOYMENT_TARGET: ${{ inputs.macos-target }}
      run: |
        uv pip install --upgrade pip
        uv pip install cmake setuptools nanobind==2.4.0
        uv pip install -e . -v

    - name: Generate package stubs
      shell: bash
      run: |
        uv pip install typing_extensions
        uv run --no-project setup.py generate_stubs

    - name: Install tests dependencies
      shell: sh
      run: |
        uv pip install numpy torch tensorflow unittest-xml-reporting

    - name: Build example extension
      shell: bash
      env:
        MACOSX_DEPLOYMENT_TARGET: ${{ inputs.macos-target }}
      run: |
        cd examples/extensions
        uv pip install -r requirements.txt
        uv run --no-project setup.py build_ext --inplace
        uv run --no-project test.py
    
    - name: Build CPP only
      shell: bash
      env:
        MACOSX_DEPLOYMENT_TARGET: ${{ inputs.macos-target }}
      run: |
        mkdir -p build
        cd build
        cmake ..
        make -j $(sysctl -n hw.ncpu)
    
    - name: Build small binary with JIT
      shell: bash
      env:
        MACOSX_DEPLOYMENT_TARGET: ${{ inputs.macos-target }}
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel \
          -DBUILD_SHARED_LIBS=ON \
          -DMLX_BUILD_CPU=OFF \
          -DMLX_BUILD_SAFETENSORS=OFF \
          -DMLX_BUILD_GGUF=OFF \
          -DMLX_METAL_JIT=ON
        make -j $(sysctl -n hw.ncpu)
    
    - name: Run Python tests with JIT
      shell: bash
      env:
        LOW_MEMORY: 1
        DEVICE: gpu
        METAL_DEVICE_WRAPPER_TYPE: 1
        METAL_DEBUG_ERROR_MODE: 0
        MACOSX_DEPLOYMENT_TARGET: ${{ inputs.macos-target }}
      run: |
        CMAKE_ARGS="-DMLX_METAL_JIT=ON" \
          uv pip install -e . -v
        uv run -m xmlrunner discover \
            -v python/tests \
            -o test-results/gpu_jit
