name: 'Build macOS release'
description: 'Build MLX releases macOS'

inputs:
  macos-target:
    description: 'macOS build target'
    required: false
    default: '15.0'
  build-backend:
    description: 'Build the backend mlx-metal package'
    required: false
    default: 'false'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10'

runs:
  using: "composite"
  steps:
    - name: Clear build environment
      shell: bash
      run: |
        echo "::group::Clear build environment"
        uv venv --clear
        uv pip install build setuptools
        python setup.py clean --all
        source .venv/bin/activate
        echo "::endgroup::"

    - name: Build Python package
      shell: bash
      env:
        DEVELOPER_DIR: /Applications/Xcode-latest.app
        MACOSX_DEPLOYMENT_TARGET: ${{ inputs.macos-target }}
      run: |
        echo "::group::Build Python package"
        MLX_BUILD_STAGE=1 python -m build -w
        python setup.py clean --all
        echo "::endgroup::"

    - name: Build backend package
      if: ${{ inputs.build-backend == 'true' }}
      shell: bash
      env:
        DEVELOPER_DIR: /Applications/Xcode-latest.app
        MACOSX_DEPLOYMENT_TARGET: ${{ inputs.macos-target }}
      run: |
        echo "::group::Build backend package"
        MLX_BUILD_STAGE=2 python -m build -w
        python setup.py clean --all
        echo "::endgroup::"

    - name: Test local packages
      if: ${{ inputs.build-backend == 'true' && inputs.macos-target == '26.0' }}
      shell: bash
      run: |
        echo "::group::Test local packages"
        uv pip install numpy torch psutil
        uv pip install dist/mlx_metal-*-macosx_26_0_arm64.whl
        uv pip install dist/mlx-*-macosx_26_0_arm64.whl
        python -m unittest discover -v python/tests
        echo "::endgroup::"
