name: 'Build CUDA wheel'
description: 'Build CUDA wheel'

inputs:
  toolkit:
    description: 'The CUDA toolkit'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build package
      shell: bash
      env:
        CMAKE_ARGS: -DMLX_BUILD_CUDA=ON -DCMAKE_CUDA_COMPILER=/usr/local/${{ inputs.toolkit }}/bin/nvcc
      run: |
        pip install auditwheel build patchelf setuptools
        python setup.py clean --all
        MLX_BUILD_STAGE=2 python -m build -w
        bash python/scripts/repair_cuda.sh
