name: 'Setup macOS Environment'
description: 'Install dependencies for macOS builds'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10'

runs:
  using: "composite"
  steps:
    - name: Install Homebrew packages
      shell: sh
      run: /opt/homebrew/bin/brew install openmpi
    
    - name: Verify MetalToolchain installed
      shell: bash
      run: xcodebuild -showComponent MetalToolchain

    - name: Install Python
      shell: sh
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        $HOME/.local/bin/uv venv --python ${{ inputs.python-version }}
        source .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
        # Search python packages in .venv
        echo PYTHONPATH=`python -c 'import sys; print(sys.path[-1])'` >> $GITHUB_ENV

    - name: Install build dependencies
      shell: sh
      run: |
        pip install --upgrade pip
        pip install cmake setuptools typing_extensions
