name: 'Setup macOS Environment'
description: 'Install dependencies for macOS builds'

inputs:
  install-mpi:
    description: 'Whether to install MPI'
    required: false
    default: 'true'
    type: boolean
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10'

runs:
  using: "composite"
  steps:
    - name: Install Homebrew packages
      shell: sh
      if: inputs.install-mpi == 'true'
      run: /opt/homebrew/bin/brew install openmpi
    
    - name: Verify MetalToolchain installed
      shell: bash
      run: xcodebuild -showComponent MetalToolchain
    
    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
          python-version: ${{ inputs.python-version }}
          activate-environment: true
