// Copyright © 2024-2026 Apple Inc.

#include "mlx/backend/cpu/jit_compiler.h"
#include "mlx/backend/common/utils.h"
#include "mlx/backend/cpu/compiled_preamble.h"

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <sstream>
#include <vector>

#include <fmt/format.h>

#if defined(_MSC_VER) && \
    (defined(_M_X64) || defined(_M_IX86) || defined(_M_AMD64))
#include <intrin.h>
#endif

namespace mlx::core {

namespace {

enum class JitPreambleTier {
  Scalar,
  HwyAvx2,
  HwyAvx3,
};

// Preamble tiers are independent of Highway's runtime-dispatched kernel
// targets. CMake only embeds the available preambles; the JIT chooses the best
// one for the local CPU and runtime compiler.

#if defined(_MSC_VER)

// Split string into array.
std::vector<std::string> str_split(const std::string& str, char delimiter) {
  std::vector<std::string> tokens;
  std::string token;
  std::istringstream tokenStream(str);
  while (std::getline(tokenStream, token, delimiter)) {
    tokens.push_back(token);
  }
  return tokens;
}

std::string get_env_var(const char* name) {
  char* value = nullptr;
  size_t size = 0;
  if (_dupenv_s(&value, &size, name) != 0 || value == nullptr) {
    return {};
  }
  std::string result(value);
  std::free(value);
  return result;
}

// Get path information about MSVC.
struct VisualStudioInfo {
  VisualStudioInfo() {
#ifdef _M_ARM64
    arch = "arm64";
#else
    arch = "x64";
#endif
    // Get path of Visual Studio.
    // Use -latest to get only the most recent installation when multiple
    // versions are installed, avoiding path concatenation issues.
    std::string pf86 = get_env_var("ProgramFiles(x86)");
    if (pf86.empty()) {
      throw std::runtime_error(
          "ProgramFiles(x86) environment variable not set.");
    }
    std::string vs_path = JitCompiler::exec(
        fmt::format(
            "\"{0}\\Microsoft Visual Studio\\Installer\\vswhere.exe\""
            " -latest -property installationPath 2>&1",
            pf86));
    if (vs_path.empty()) {
      throw std::runtime_error("Can not find Visual Studio.");
    }
    // Trim any trailing whitespace/newlines from the path
    vs_path.erase(
        std::find_if(
            vs_path.rbegin(),
            vs_path.rend(),
            [](unsigned char ch) { return !std::isspace(ch); })
            .base(),
        vs_path.end());
    // Read the envs from vcvarsall.
    std::string envs = JitCompiler::exec(
        fmt::format(
            "\"{0}\\VC\\Auxiliary\\Build\\vcvarsall.bat\" {1} >NUL 2>&1 && set",
            vs_path,
            arch));
    for (const std::string& line : str_split(envs, '\n')) {
      // Each line is in the format "ENV_NAME=values".
      auto pos = line.find_first_of('=');
      if (pos == std::string::npos || pos == 0 || pos == line.size() - 1)
        continue;
      std::string name = line.substr(0, pos);
      std::string value = line.substr(pos + 1);
      if (name == "INCLUDE") {
        includepaths = str_split(value, ';');
      } else if (name == "LIB") {
        libpaths = str_split(value, ';');
      } else if (name == "VCToolsInstallDir" || name == "VCTOOLSINSTALLDIR") {
        msvc_cl = fmt::format("{0}\\bin\\Host{1}\\{1}\\cl.exe", value, arch);
      }
    }

    // Check for clang-cl bundled with Visual Studio.
    std::string clang_cl_path = fmt::format(
        "{0}\\VC\\Tools\\Llvm\\{1}\\bin\\clang-cl.exe", vs_path, arch);
    if (std::filesystem::exists(clang_cl_path)) {
      clang_cl = clang_cl_path;
    }
  }

  std::string compiler(bool use_include, JitPreambleTier tier) const {
    if (tier == JitPreambleTier::HwyAvx3 && !clang_cl.empty()) {
      return clang_cl;
    }
    if (use_include) {
      // With installed headers, either cl.exe or clang-cl can parse the source.
      // Prefer cl.exe since it is part of the standard Visual Studio C++
      // toolchain.
      return !msvc_cl.empty() ? msvc_cl : clang_cl;
    }

    // Without installed headers, fall back to the embedded prebuilt preamble.
    // It was generated by the build compiler and may contain compiler-specific
    // builtins, so prefer the same compiler family when possible.
#ifdef __clang__
    return !clang_cl.empty() ? clang_cl : msvc_cl;
#else
    return !msvc_cl.empty() ? msvc_cl : clang_cl;
#endif
  }

  std::string arch;
  std::string msvc_cl;
  std::string clang_cl;
  std::vector<std::string> includepaths;
  std::vector<std::string> libpaths;
};

const VisualStudioInfo& GetVisualStudioInfo() {
  static VisualStudioInfo info;
  return info;
}

#endif // defined(_MSC_VER)

#if !defined(_MSC_VER)
std::string jit_cxx_compiler() {
  if (const char* compiler = std::getenv("MLX_JIT_CXX");
      compiler && compiler[0] != '\0') {
    return compiler;
  }
#if defined(__clang__)
  return "clang++";
#else
  return "g++";
#endif
}

std::string command_executable(const std::string& executable) {
#if defined(_WIN32)
  if (executable.find_first_of(" \t\"") == std::string::npos) {
    return executable;
  }
#endif
  return fmt::format("\"{}\"", executable);
}

std::string command_path(const std::filesystem::path& path) {
#if defined(_WIN32)
  return path.generic_string();
#else
  return path.string();
#endif
}
#endif // !defined(_MSC_VER)

std::filesystem::path find_jit_include_dir(bool require_highway) {
  std::vector<std::filesystem::path> roots;
  auto binary_dir = current_binary_dir();
  roots.push_back(binary_dir);
#if !defined(_WIN32)
  roots.push_back(binary_dir.parent_path());
#endif

  for (const auto& root : roots) {
    auto include_dir = root / "include";
    auto preamble_header = include_dir / "mlx/backend/cpu/compiled_preamble.h";
    auto highway_header = include_dir / "hwy/highway.h";
    if (std::filesystem::exists(preamble_header) &&
        (!require_highway || std::filesystem::exists(highway_header))) {
      return include_dir;
    }
  }
  return {};
}

bool supports_hwy_avx2_preamble() {
#if defined(_MSC_VER)

#if defined(_M_X64) || defined(_M_IX86) || defined(_M_AMD64)
  int info[4];
  __cpuid(info, 0);
  if (info[0] < 7) {
    return false;
  }
  __cpuid(info, 1);
  bool os_avx = (info[2] & (1 << 27)) && (info[2] & (1 << 28));
  bool fma = info[2] & (1 << 12);
  bool f16c = info[2] & (1 << 29);
  if (!os_avx || !fma || !f16c) {
    return false;
  }
  unsigned long long xcr0 = _xgetbv(0);
  if ((xcr0 & 0x6) != 0x6) {
    return false;
  }
  __cpuidex(info, 7, 0);
  bool avx2 = info[1] & (1 << 5);
  bool bmi2 = info[1] & (1 << 8);
  return avx2 && bmi2;
#else
  return false;
#endif // defined(_M_X64) || defined(_M_IX86) || defined(_M_AMD64)

#elif defined(__GNUC__) || defined(__clang__)

#if defined(__x86_64__) || defined(__i386__) || defined(__amd64__)
  __builtin_cpu_init();
  return __builtin_cpu_supports("avx2") && __builtin_cpu_supports("bmi2") &&
      __builtin_cpu_supports("fma") && __builtin_cpu_supports("f16c");
#else
  return false;
#endif

#else
  return false;
#endif // defined(_MSC_VER)
}

#if defined(MLX_HAVE_JIT_PREAMBLE_HWY_AVX3)

bool supports_hwy_avx3_preamble() {
#if defined(_MSC_VER)

#if defined(_M_X64) || defined(_M_IX86) || defined(_M_AMD64)
  int info[4];
  __cpuid(info, 0);
  if (info[0] < 7) {
    return false;
  }
  __cpuid(info, 1);
  const uint32_t ecx = static_cast<uint32_t>(info[2]);
  const bool os_avx = (ecx & (1u << 27)) && (ecx & (1u << 28));
  const bool fma = ecx & (1u << 12);
  const bool f16c = ecx & (1u << 29);
  if (!os_avx) {
    return false;
  }
  const unsigned long long xcr0 = _xgetbv(0);
  if ((xcr0 & 0xE6) != 0xE6) {
    return false;
  }
  __cpuidex(info, 7, 0);
  const uint32_t ebx = static_cast<uint32_t>(info[1]);
  const bool bmi2 = ebx & (1u << 8);
  const bool avx512f = ebx & (1u << 16);
  const bool avx512dq = ebx & (1u << 17);
  const bool avx512cd = ebx & (1u << 28);
  const bool avx512bw = ebx & (1u << 30);
  const bool avx512vl = ebx & (1u << 31);
  return avx512f && avx512dq && avx512cd && avx512bw && avx512vl && bmi2 &&
      fma && f16c;
#else
  return false;
#endif // defined(_M_X64) || defined(_M_IX86) || defined(_M_AMD64)

#elif defined(__GNUC__) || defined(__clang__)

#if defined(__x86_64__) || defined(__i386__) || defined(__amd64__)
  __builtin_cpu_init();
  return __builtin_cpu_supports("avx512f") &&
      __builtin_cpu_supports("avx512dq") &&
      __builtin_cpu_supports("avx512cd") &&
      __builtin_cpu_supports("avx512bw") &&
      __builtin_cpu_supports("avx512vl") && __builtin_cpu_supports("bmi2") &&
      __builtin_cpu_supports("fma") && __builtin_cpu_supports("f16c");
#else
  return false;
#endif

#else
  return false;
#endif
}

bool can_compile_hwy_avx3_preamble() {
#if defined(_MSC_VER)
  return !GetVisualStudioInfo().clang_cl.empty();
#else
  return true;
#endif
}

#endif // defined(MLX_HAVE_JIT_PREAMBLE_HWY_AVX3)

JitPreambleTier select_jit_preamble_tier() {
#if defined(MLX_HAVE_JIT_PREAMBLE_HWY_AVX3)
  if (supports_hwy_avx3_preamble() && can_compile_hwy_avx3_preamble()) {
    return JitPreambleTier::HwyAvx3;
  }
#endif
#if defined(MLX_HAVE_JIT_PREAMBLE_HWY_AVX2)
  if (supports_hwy_avx2_preamble()) {
    return JitPreambleTier::HwyAvx2;
  }
#endif
  return JitPreambleTier::Scalar;
}

JitPreambleTier jit_preamble_tier() {
  static JitPreambleTier tier = select_jit_preamble_tier();
  return tier;
}

bool use_hwy_avx2_preamble() {
  return jit_preamble_tier() == JitPreambleTier::HwyAvx2;
}

bool use_hwy_avx3_preamble() {
  return jit_preamble_tier() == JitPreambleTier::HwyAvx3;
}

} // namespace

const std::tuple<bool, std::string, std::string>& JitCompiler::get_preamble() {
  static auto scalar_preamble =
      []() -> std::tuple<bool, std::string, std::string> {
    // Check whether the headers are shipped with the binary, if so use the
    // preamble from the headers, otherwise use the prebuilt one embedded in
    // binary, which may not work with all compilers.
    auto include_dir = find_jit_include_dir(false);
    if (!include_dir.empty()) {
      return std::make_tuple(
          true,
          include_dir.string(),
          "#include \"mlx/backend/cpu/compiled_preamble.h\"\n");
    } else {
      return std::make_tuple(false, "", get_prebuilt_preamble());
    }
  }();
#if defined(MLX_HAVE_JIT_PREAMBLE_HWY_AVX2)
  static auto avx2_preamble =
      []() -> std::tuple<bool, std::string, std::string> {
    // Check whether the headers are shipped with the binary, if so use the
    // preamble from the headers, otherwise use the prebuilt one embedded in
    // binary, which may not work with all compilers.
    auto include_dir = find_jit_include_dir(true);
    if (!include_dir.empty()) {
      return std::make_tuple(
          true,
          include_dir.string(),
          "#define MLX_USE_HIGHWAY_JIT_SIMD\n"
          "#define HWY_COMPILE_ONLY_STATIC\n"
          "#define HWY_DISABLE_PCLMUL_AES\n"
          "#include \"mlx/backend/cpu/compiled_preamble.h\"\n");
    } else {
      // Installed MLX headers alone are not enough for the Highway SIMD facade.
      // Wheels can still use the embedded prebuilt AVX2 preamble without
      // shipping Highway headers as a runtime payload.
      return std::make_tuple(false, "", get_prebuilt_preamble_avx2());
    }
  }();
#if defined(MLX_HAVE_JIT_PREAMBLE_HWY_AVX3)
  static auto avx3_preamble =
      []() -> std::tuple<bool, std::string, std::string> {
    auto include_dir = find_jit_include_dir(true);
    if (!include_dir.empty()) {
      return std::make_tuple(
          true,
          include_dir.string(),
          "#define MLX_USE_HIGHWAY_JIT_SIMD\n"
          "#define HWY_COMPILE_ONLY_STATIC\n"
          "#define HWY_DISABLE_PCLMUL_AES\n"
          "#include \"mlx/backend/cpu/compiled_preamble.h\"\n");
    } else {
      return std::make_tuple(false, "", get_prebuilt_preamble_avx3());
    }
  }();
  if (use_hwy_avx3_preamble()) {
    return avx3_preamble;
  }
#endif
  if (use_hwy_avx2_preamble()) {
    return avx2_preamble;
  }
#endif
  return scalar_preamble;
}

bool JitCompiler::available() {
#ifdef _MSC_VER
  static bool result = [] {
    try {
      bool use_include = std::get<0>(get_preamble());
      const auto& info = GetVisualStudioInfo();
      return !info.compiler(use_include, jit_preamble_tier()).empty();
    } catch (...) {
      return false;
    }
  }();
  return result;
#else
#ifdef _WIN32
  // Windows CPU JIT is only enabled for the Visual Studio ABI path above.
  // MinGW-style JIT code was slower than the runtime-dispatched kernels in
  // testing and has a more fragile runtime DLL discovery story.
  return false;
#else
  static int result = std::system(
      fmt::format(
          "{} --version > /dev/null 2>&1",
          command_executable(jit_cxx_compiler()))
          .c_str());
  return result == 0;
#endif
#endif
}

std::string JitCompiler::build_command(
    const std::filesystem::path& dir,
    const std::string& source_file_name,
    const std::string& shared_lib_name) {
  auto& [use_include, include_dir, preamble] = get_preamble();
#ifdef _MSC_VER
  std::string compiler_flags;
  if (use_include) {
    compiler_flags += fmt::format(" /I \"{}\"", include_dir);
  }
  const VisualStudioInfo& info = GetVisualStudioInfo();
  std::string compiler = info.compiler(use_include, jit_preamble_tier());
  for (const std::string& inc : info.includepaths) {
    if (!inc.empty()) {
      compiler_flags += fmt::format(" /I \"{}\"", inc);
    }
  }
  std::string libpaths;
  for (const std::string& lib : info.libpaths) {
    libpaths += fmt::format(" /libpath:\"{}\"", lib);
  }
  // clang-cl accepts the same flags as cl.exe (/LD, /EHsc, etc.)
  // but we add -Wno-everything to suppress warnings from system and shipped
  // MLX headers.
  if (!info.clang_cl.empty() && compiler == info.clang_cl) {
    compiler_flags += " -Wno-everything";
  }
#if defined(MLX_HAVE_JIT_PREAMBLE_HWY_AVX2) || \
    defined(MLX_HAVE_JIT_PREAMBLE_HWY_AVX3)
  if (use_hwy_avx3_preamble()) {
    compiler_flags +=
        " /clang:-mavx512f /clang:-mavx512vl /clang:-mavx512bw"
        " /clang:-mavx512dq /clang:-mavx512cd /clang:-mbmi2"
        " /clang:-mfma /clang:-mf16c";
  } else if (use_hwy_avx2_preamble()) {
    compiler_flags += " /arch:AVX2";
  }
#endif
  return fmt::format(
      "\""
      "cd /D \"{0}\" && "
      "\"{1}\" /LD /EHsc /MD /Ox /nologo /std:c++17{2} \"{3}\" "
      "/link /out:\"{4}\" {5} 2>&1"
      "\"",
      dir.string(),
      compiler,
      compiler_flags,
      source_file_name,
      shared_lib_name,
      libpaths);
#else
  std::string extra_flags;
  if (use_include) {
    extra_flags = fmt::format("-I \"{}\"", include_dir);
  }
#if defined(MLX_HAVE_JIT_PREAMBLE_HWY_AVX2) || \
    defined(MLX_HAVE_JIT_PREAMBLE_HWY_AVX3)
  if (use_hwy_avx3_preamble()) {
    if (!extra_flags.empty()) {
      extra_flags += " ";
    }
    extra_flags +=
        "-mavx512f -mavx512vl -mavx512bw -mavx512dq -mavx512cd "
        "-mbmi2 -mfma -mf16c";
  } else if (use_hwy_avx2_preamble()) {
    if (!extra_flags.empty()) {
      extra_flags += " ";
    }
    // JIT code is compiled locally, so it can pin to the current CPU after the
    // runtime feature check while the shipped MLX binary remains baseline-safe.
    extra_flags += "-mavx2 -mbmi2 -mfma -mf16c";
  }
#endif
  return fmt::format(
      "{} -std=c++17 -O3 -Wall -fPIC -shared {} \"{}\" -o \"{}\" 2>&1",
      command_executable(jit_cxx_compiler()),
      extra_flags,
      command_path(dir / source_file_name),
      command_path(dir / shared_lib_name));
#endif
}

std::string JitCompiler::exec(const std::string& cmd) {
#ifdef _MSC_VER
  FILE* pipe = _popen(cmd.c_str(), "r");
#else
  FILE* pipe = popen(cmd.c_str(), "r");
#endif
  if (!pipe) {
    throw std::runtime_error("popen() failed.");
  }
  char buffer[128];
  std::string ret;
  while (fgets(buffer, sizeof(buffer), pipe)) {
    ret += buffer;
  }
  // Trim trailing whitespace.
  ret.erase(
      std::find_if(
          ret.rbegin(),
          ret.rend(),
          [](unsigned char ch) { return !std::isspace(ch); })
          .base(),
      ret.end());

#ifdef _MSC_VER
  int status = _pclose(pipe);
#else
  int status = pclose(pipe);
#endif
  if (status == -1) {
    throw std::runtime_error("pclose() failed.");
  }
#if defined(_WIN32) || defined(__FreeBSD__)
  int code = status;
#else
  int code = WEXITSTATUS(status);
#endif
  if (code != 0) {
    throw std::runtime_error(
        fmt::format(
            "Failed to execute command with return code {0}: \"{1}\", "
            "the output is: {2}",
            code,
            cmd,
            ret));
  }
  return ret;
}

} // namespace mlx::core
