name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
      # For testing CI without starting a pull request:
      - test/*

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check_lint:
    name: Check Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: pre-commit/action@v3.0.1

  build_and_test:
    name: ${{ matrix.os }} (${{ matrix.toolkit }}, ${{ matrix.arch }})
    if: github.repository == 'ml-explore/mlx'
    needs: check_lint
    strategy:
      fail-fast: false
      matrix:
        os: ['Linux', 'Windows']
        arch: ['x86_64', 'aarch64']
        toolkit: ['cpu', 'cuda-12.6', 'cuda-12.9', 'cuda-13.0']
        exclude:
          # CUDA does not support Windows on arm.
          - os: 'Windows'
            arch: 'aarch64'
            toolkit: 'cuda-12.6'
          - os: 'Windows'
            arch: 'aarch64'
            toolkit: 'cuda-12.9'
          - os: 'Windows'
            arch: 'aarch64'
            toolkit: 'cuda-13.0'
          # CUDA 12.6 does not compile with CUTLASS on Windows.
          - os: 'Windows'
            arch: 'x86_64'
            toolkit: 'cuda-12.6'
    runs-on: |-
      ${{ case(matrix.os == 'Windows',
               case(matrix.arch == 'aarch64', 'windows-11-arm',
                    'windows-2022'),
               case(matrix.arch == 'x86_64' && startsWith(matrix.toolkit, 'cuda'), 'gpu-t4-4-core',
                    matrix.arch == 'aarch64', 'ubuntu-22.04-arm',
                    'ubuntu-22.04'))
      }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        id: setup
        with:
          toolkit: ${{ matrix.toolkit }}
      - uses: ./.github/actions/build
        with:
          cmake-args: ${{ steps.setup.outputs.cmake-args }}
          # For MSVC, Ninja/Release is the only config supported by ccache.
          debug: ${{ matrix.os != 'Windows' }}
      - uses: ./.github/actions/test-linux
        if: matrix.os == 'Linux' && (matrix.toolkit == 'cpu' || matrix.arch == 'x86_64')
      - uses: ./.github/actions/test-windows
        if: matrix.os == 'Windows' && matrix.toolkit == 'cpu'

  mac_build:
    name: macOS (${{ matrix.macos-target }}, ${{ matrix.toolkit }})
    if: github.repository == 'ml-explore/mlx'
    strategy:
      matrix:
        macos-target: ['14.0', '15.0', '26.2']
        toolkit: ['cpu', 'metal', 'jit']
    runs-on: 'macos-26'
    needs: check_lint
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        id: setup
        with:
          toolkit: ${{ matrix.toolkit }}
          ccache-key: 'test-${{ matrix.macos-target }}'
          # Use the compile cache of metal build for all builds.
          ccache-save: ${{ matrix.toolkit == 'metal' }}
          ccache-toolkit: 'metal'
      - uses: ./.github/actions/build-macos
        with:
          cmake-args: ${{ steps.setup.outputs.cmake-args }}
          macos-target: ${{ matrix.macos-target }}
      - uses: ./.github/actions/test-macos
        if: matrix.toolkit == 'cpu'
        with:
          toolkit: 'cpu'
      - uses: actions/upload-artifact@v7
        if: matrix.toolkit == 'metal'
        with:
          name: mlx-${{ matrix.toolkit }}-macos${{ matrix.macos-target }}
          path: |
            dist/mlx-*.whl
            build/mlx/backend/metal/kernels/mlx.metallib
            build/tests/tests
          if-no-files-found: error

  mac_test:
    name: Test macOS
    if: github.repository == 'ml-explore/mlx'
    runs-on: [self-hosted, macos]
    needs: mac_build
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          toolkit: 'metal'
          use-ccache: false
      - uses: actions/download-artifact@v8
        with:
          path: artifact
          pattern: mlx-metal-*
      - run: ls -lhR artifact
      - uses: ./.github/actions/test-macos
        with:
          toolkit: 'metal'

  build_documentation:
    name: Build Documentation
    if: github.repository == 'ml-explore/mlx'
    runs-on: ubuntu-22.04
    needs: check_lint
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/build-docs

  linux_sanitizer_build_and_test:
    name: Linux Sanitizer Tests (${{ matrix.sanitizer }})
    needs: check_lint
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [ASAN, UBSAN]
        # todo 12/16/2025: enable TSAN later + consider enabling ASAN for GPU backend tests.
        # sanitizer: [ASAN, UBSAN, TSAN]
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -y
          sudo apt-get install -y \
            build-essential \
            libblas-dev \
            liblapacke-dev \
            libopenblas-dev \
            cmake \
            clang \
            git
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Linux Build and Test with ${{ matrix.sanitizer }}
        run: |
          bash .github/scripts/build-sanitizer-tests.sh ${{ matrix.sanitizer }}

  linux_fedora_build_cpp:
    name: Linux Fedora (${{ matrix.arch }})
    needs: check_lint
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: ubuntu-22.04
            arch: x86_64
          - host: ubuntu-22.04-arm
            arch: aarch64

    runs-on: ${{ matrix.host }}
    container:
      image: fedora:42
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: CPP Build Test - No Release
        run: |
          bash ./.github/scripts/setup+build-cpp-linux-fedora-container.sh
